Gormv2: # 只针对 gorm  操作数据库有效
  UseDbType: "mysql"   # admin 系统目前只支持mysql数据库，请勿修改为其他数据库
  Mysql:
    IsInitGlobalGormMysql: 1    # 随项目启动为gorm db初始化一个全局 variable.GormDbMysql（完全等于*gorm.Db）,正确配置数据库，该值必须设置为: 1
    SlowThreshold: 30            # 慢 SQL 阈值(sql执行时间超过此时间单位（秒），就会触发系统日志记录)
    Write:
      Host: "127.0.0.1"
      DataBase: "db_ginskeleton2"
      Port: 3306
      Prefix: "tb_"   #  目前没有用到该配置项
      User: "root"
      Pass: "YourDbPassword"  # 修改为你自己的数据库密码
      Charset: "utf8"
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60    # 连接不活动时的最大生存时间(秒)
      #ReConnectInterval: 1    # 保留项,重连数据库间隔秒数
      #PingFailRetryTimes: 3   # 保留项,最大重连次数
    IsOpenReadDb: 0                     # 是否开启读写分离配置（1=开启、0=关闭），IsOpenReadDb=1,Read 部分参数有效，否则Read部分参数直接忽略
    Read:
      Host: "192.168.1.10"
      DataBase: "db_ginskeleton2"
      Port: 3306                        #注意，非3306，请自行调整
      Prefix: "tb_"
      User: "root"
      Pass: "YourDbPassword"  # 修改为你自己的数据库密码
      Charset: "utf8"
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60

  SqlServer:
    IsInitGlobalGormSqlserver: 0 # 随项目启动为gorm db初始化一个全局 variable.GormDbMysql（完全等于*gorm.Db）,正确配置数据库，该值必须设置为: 1
    SlowThreshold: 30
    Write:
      Host: "127.0.0.1"
      DataBase: "db_ginskeleton2"
      Port: 1433
      Prefix: "tb_"
      User: "Sa"
      Pass: "secret2017"
      #ReConnectInterval: 1    # 保留项,重连数据库间隔秒数
      #PingFailRetryTimes: 3   # 保留项,最大重连次数
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60
    IsOpenReadDb: 0            # 是否开启读写分离配置（1=开启、0=关闭），IsOpenReadDb=1,Read  部分参数有效，否则Read部分参数直接忽略
    Read:
      Host: "127.0.0.1"
      DataBase: "db_ginskeleton2"
      Port: 1433
      Prefix: "tb_"
      User: "Sa"
      Pass: "YourDbPassword"
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60

  PostgreSql:
    IsInitGlobalGormPostgreSql: 0  # 随项目启动为gorm db初始化一个全局 variable.GormDbMysql（完全等于*gorm.Db）,正确配置数据库，该值必须设置为: 1
    SlowThreshold: 30
    Write:
      Host: "127.0.0.1"
      DataBase: "db_ginskeleton2"
      Port: 5432
      Prefix: "tb_"
      User: "postgres"
      Pass: "YourDbPassword"
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60
    #ReConnectInterval: 1    # 保留项,重连数据库间隔秒数
    #PingFailRetryTimes: 3   # 保留项,最大重连次数
    IsOpenReadDb: 0            # 是否开启读写分离配置（1=开启、0=关闭），IsOpenReadDb=1,Read  部分参数有效，否则Read部分参数直接忽略
    Read:
      Host: "127.0.0.1"
      DataBase: "db_ginskeleton2"
      Port: 5432
      Prefix: "tb_"
      User: "postgres"
      Pass: "YourDbPassword"
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60
